sudo: required
services:
  - docker

before_install:
  - docker build -t bjmashele/react-aws-boilerplate -f Dockerfile.dev . 

script:
  - docker run -e CI=true bjmashele/react-aws-boilerplate npm run test # Use -e CI=true to override npm run test default behavior.
  